
development:
  adapter: postgresql
  encoding: unicode
  database: angular_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: angular_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres
